-- 코드를 입력하세요
SELECT TITLE, A.BOARD_ID, REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS A
INNER JOIN USED_GOODS_REPLY AS B USING (BOARD_ID)
WHERE YEAR(A.CREATED_DATE) = 2022 and MONTH(A.CREATED_DATE) = 10
ORDER BY DATE(B.CREATED_DATE), TITLE ASC